import Header from "../components/Header/Header.js";
import './globals.scss';
import styles from "./globals.module.scss";
import Delete from "@/components/ViewInvoice/Delete/Delete.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.layout}>
        <Header/>
        {children}
        <Delete/>
      </body>
    </html>
  );
}
